language: node_js
node_js:
- 10.8.0
addons:
  ssh_known_hosts: cruciblemud.com
before_script:
cache:
  directories:
  - node_modules
script:
- if [ "$TRAVIS_BRANCH" = "develop" ]; then npm run build:develop; fi
- if [ "$TRAVIS_BRANCH" = "master" ]; then npm run build; fi
before_deploy:
- openssl aes-256-cbc -K $encrypted_185975ce55b6_key -iv $encrypted_185975ce55b6_iv -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -am --stats --delete-after $TRAVIS_BUILD_DIR/build/* root@cruciblemud.com:/var/www/develop && ssh root@cruciblemud.com 'systemctl restart apache2'
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: rsync -am --stats --delete-after $TRAVIS_BUILD_DIR/build/* root@cruciblemud.com:/var/www/html && ssh root@cruciblemud.com 'systemctl restart apache2'
    on:
      branch: master
